import type { Job } from '../types';

export const mockJobs: Job[] = [
  {
    id: 'job-1',
    month: 'October',
    year: 2025,
    campaignName: 'Q4 Warranty Push',
    status: 'complete',
    createdAt: new Date('2025-09-15'),
    updatedAt: new Date('2025-10-01'),
    buckslip1: {
      id: 'file-1',
      name: 'warranty-promo-1.pdf',
      url: '#',
      uploadedAt: new Date('2025-09-15'),
    },
    buckslip2: {
      id: 'file-2',
      name: 'warranty-promo-2.pdf',
      url: '#',
      uploadedAt: new Date('2025-09-15'),
    },
    buckslip3: {
      id: 'file-3',
      name: 'warranty-promo-3.pdf',
      url: '#',
      uploadedAt: new Date('2025-09-15'),
    },
    letterReply: {
      id: 'file-4',
      name: 'letter-template.pdf',
      url: '#',
      uploadedAt: new Date('2025-09-15'),
    },
    outerEnvelope: {
      id: 'file-5',
      name: 'envelope-design.pdf',
      url: '#',
      uploadedAt: new Date('2025-09-15'),
    },
    mailList: {
      id: 'file-6',
      name: 'customer-list-oct.csv',
      url: '#',
      uploadedAt: new Date('2025-09-15'),
    },
    mailCount: 5000,
    ratePerPiece: 0.75,
  },
  {
    id: 'job-2',
    month: 'November',
    year: 2025,
    campaignName: 'Holiday Warranty Campaign',
    status: 'proofing',
    createdAt: new Date('2025-10-01'),
    updatedAt: new Date('2025-10-05'),
    buckslip1: {
      id: 'file-7',
      name: 'holiday-promo-1.pdf',
      url: '#',
      uploadedAt: new Date('2025-10-01'),
    },
    buckslip2: {
      id: 'file-8',
      name: 'holiday-promo-2.pdf',
      url: '#',
      uploadedAt: new Date('2025-10-01'),
    },
    buckslip3: {
      id: 'file-9',
      name: 'holiday-promo-3.pdf',
      url: '#',
      uploadedAt: new Date('2025-10-01'),
    },
    letterReply: {
      id: 'file-10',
      name: 'holiday-letter.pdf',
      url: '#',
      uploadedAt: new Date('2025-10-01'),
    },
    outerEnvelope: {
      id: 'file-11',
      name: 'holiday-envelope.pdf',
      url: '#',
      uploadedAt: new Date('2025-10-01'),
    },
    mailList: {
      id: 'file-12',
      name: 'customer-list-nov.csv',
      url: '#',
      uploadedAt: new Date('2025-10-01'),
    },
    mailCount: 6500,
    ratePerPiece: 0.75,
  },
  {
    id: 'job-3',
    month: 'December',
    year: 2025,
    campaignName: 'Year-End Warranty Reminder',
    status: 'draft',
    createdAt: new Date('2025-10-06'),
    updatedAt: new Date('2025-10-06'),
    mailCount: 4800,
    ratePerPiece: 0.75,
  },
];
